# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactTestApp' do
  pod 'AppCenter/Push', '~> 1.9.0'
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactTestApp

  

  platform :ios, '9.0'
  target 'ReactTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactTestApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactTestApp-tvOS

  target 'ReactTestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
